dao-plugin/DaoGrailsPlugin.groovy, dao-plugin/src/groovy/grails/plugin/dao/DaoMessage.groovy, dao-plugin/src/groovy/grails/plugin/dao/DaoUtil.groovy, dao-plugin/src/groovy/grails/plugin/dao/DomainException.groovy, dao-plugin/src/groovy/grails/plugin/dao/GormDaoSupport.groovy
=> Remove formatParams method

dao-plugin/DaoGrailsPlugin.groovy, dao-plugin/application.properties, dao-plugin/grails-app/conf/BuildConfig.groovy, dao-plugin/grails-app/conf/DataSource.groovy, dao-plugin/test/integration/grails/plugin/dao/DomainMethodsTests.groovy
=> 6 grails255 hibernate4 upgrade

dao-plugin/build.gradle, dao-plugin/grails-app/services/gorm/tools/DbDialectService.groovy, dao-plugin/grails-app/services/grails/plugin/dao/DbDialectService.groovy, dao-plugin/src/main/groovy/gorm/tools/GormUtils.groovy, dao-plugin/src/main/groovy/gorm/tools/Pager.groovy, dao-plugin/src/main/groovy/gorm/tools/beans/BeanPathTools.groovy, dao-plugin/src/main/groovy/gorm/tools/beans/DaoDelegatingBean.groovy, dao-plugin/src/main/groovy/gorm/tools/beans/DateUtil.groovy, dao-plugin/src/main/groovy/gorm/tools/beans/DelegatingBean.groovy, dao-plugin/src/main/groovy/gorm/tools/beans/MapFlattener.groovy, dao-plugin/src/main/groovy/gorm/tools/beans/MultiFormatDateConverter.groovy, dao-plugin/src/main/groovy/gorm/tools/criteria/CriteriaUtils.groovy, dao-plugin/src/main/groovy/gorm/tools/criteria/GormHibernateCriteriaBuilder.groovy, dao-plugin/src/main/groovy/gorm/tools/query/ListParseUtil.groovy, dao-plugin/src/main/groovy/grails/plugin/dao/DaoPluginHelper.groovy, dao-plugin/src/main/groovy/grails/plugin/dao/RestDaoController.groovy, dao-plugin/src/test/groovy/gorm/tools/PagerSpec.groovy, dao-plugin/src/test/groovy/gorm/tools/beans/BeanPathToolsSpec.groovy, dao-plugin/src/test/groovy/gorm/tools/beans/DateUtilTest.groovy, dao-plugin/src/test/groovy/gorm/tools/beans/MapFlattenerTest.groovy, dao-plugin/src/test/groovy/gorm/tools/query/StringUtilTests.groovy
=> Merge rally griner

docs/index.md, gradle.properties, plugin/src/main/groovy/gorm/tools/hibernate/criteria/CriteriaUtils.groovy, plugin/src/main/groovy/gorm/tools/hibernate/criteria/Statements.groovy, plugin/src/main/groovy/grails/plugin/dao/DaoDomainTrait.groovy, plugin/src/main/groovy/grails/plugin/dao/GormDaoSupport.groovy, plugin/src/main/groovy/grails/plugin/dao/RestDaoController.groovy, test-projects/app/build.gradle, test-projects/app/grails-app/domain/daoapp/Address.groovy, test-projects/app/grails-app/domain/daoapp/Org.groovy, test-projects/app/grails-app/init/daoapp/BootStrap.groovy, test-projects/app/src/integration-test/groovy/daoapp/OrgSpec.groovy, test-projects/app/src/integration-test/groovy/gorm/tools/CriteriaUtilsSpec.groovy
=> Intelligent criteria, basic implementation

docs/mapql.md
=> mapQl docs changes

plugin/src/main/groovy/gorm/tools/beans/BeanPathTools.groovy, plugin/src/main/groovy/gorm/tools/beans/DateUtil.groovy, plugin/src/main/groovy/gorm/tools/beans/MapFlattener.groovy, plugin/src/main/groovy/gorm/tools/hibernate/criteria/CriteriaUtils.groovy, plugin/src/main/groovy/gorm/tools/hibernate/criteria/Statements.groovy, plugin/src/main/groovy/gorm/tools/idgen/SpringIdGenerator.groovy, plugin/src/main/groovy/grails/plugin/dao/DaoDomainTrait.groovy, plugin/src/main/groovy/grails/plugin/dao/GormDaoSupport.groovy, plugin/src/main/groovy/grails/plugin/dao/RestDaoController.groovy, plugin/src/test/groovy/gorm/tools/beans/BeanPathToolsSpec.groovy, plugin/src/test/groovy/gorm/tools/beans/MapFlattenerTest.groovy
=> 32 fixmes cleanup

plugin/build.gradle, plugin/src/main/groovy/gorm/tools/GormUtils.groovy, plugin/src/main/groovy/gorm/tools/hibernate/criteria/CriteriaUtils.groovy, plugin/src/main/groovy/gorm/tools/hibernate/criteria/DynamicCriteriaBuilder.groovy, plugin/src/main/groovy/gorm/tools/hibernate/criteria/Statements.groovy, plugin/src/main/groovy/gorm/tools/mango/MangoCriteria.groovy, plugin/src/main/groovy/grails/plugin/dao/DaoDomainTrait.groovy, plugin/src/test/groovy/gorm/tools/PagerSpec.groovy, plugin/src/test/groovy/grails/plugin/dao/DaoUtilsTests.groovy, plugin/src/test/groovy/grails/plugin/dao/DomainExceptionSpec.groovy
=> Fix codenarc warnings

plugin/src/main/groovy/gorm/tools/testing/DaoHibernateSpec.groovy, plugin/src/test/groovy/gorm/tools/dao/GormDaoSpec.groovy
=> #53 Add DaoHibernateSpec

docs/working-with-dates.md, plugin/src/main/groovy/gorm/tools/beans/MultiFormatDateConverter.groovy
=> Added docs for MultiFormatDateConverter #48

plugin/src/main/groovy/gorm/tools/Pager.groovy, plugin/src/test/groovy/gorm/tools/PagerSpec.groovy
=> Added Pager docs and specs #55

docs/dao.md, examples/benchmarks/grails-app/services/gpbench/BenchmarkDatabindingService.groovy, examples/benchmarks/src/main/groovy/gpbench/benchmarks/GparsBaselineBenchmark.groovy, examples/benchmarks/src/main/groovy/gpbench/benchmarks/GparsDaoBenchmark.groovy, plugin/src/main/groovy/gorm/tools/GormUtils.groovy, plugin/src/main/groovy/gorm/tools/dao/GormDao.groovy, plugin/src/main/groovy/gorm/tools/databinding/GormMapBinder.groovy, plugin/src/main/groovy/gorm/tools/databinding/MapBinder.groovy, plugin/src/main/groovy/gorm/tools/testing/DaoTestHelper.groovy, plugin/src/main/groovy/grails/plugin/dao/DaoPluginHelper.groovy, plugin/src/test/groovy/gorm/tools/databinding/FastBinderUnitSpec.groovy, plugin/src/test/groovy/gorm/tools/databinding/GormMapBinderUnitSpec.groovy
=> 81 map binder

docs/dao.md, plugin/src/main/groovy/gorm/tools/async/AsyncBatchSupport.groovy, plugin/src/main/groovy/gorm/tools/dao/DaoUtil.groovy, plugin/src/test/groovy/gorm/tools/async/GparsBatchSupportSpec.groovy
=> 86 async batch support

docs/dao.md
=> #51 Add docs for external event listeners

examples/benchmarks/grails-app/conf/application.groovy, examples/benchmarks/grails-app/conf/application.yml, examples/benchmarks/grails-app/conf/spring/resources.groovy, examples/benchmarks/grails-app/init/gpbench/BootStrap.groovy, plugin/grails-app/conf/application.groovy, plugin/grails-app/conf/application.yml, plugin/src/main/groovy/gorm/tools/idgen/JdbcIdGenerator.groovy, plugin/src/main/groovy/gorm/tools/repository/api/RepositoryApi.groovy, plugin/src/main/groovy/gorm/tools/repository/errors/RepoExceptionSupport.groovy, plugin/src/main/groovy/gorm/tools/testing/GormToolsHibernateSpec.groovy, plugin/src/main/groovy/gorm/tools/testing/GormToolsTestHelper.groovy, plugin/src/main/groovy/grails/plugin/gormtools/GormToolsGrailsPlugin.groovy, plugin/src/main/groovy/grails/plugin/gormtools/GormToolsPluginHelper.groovy, plugin/src/main/groovy/org/grails/orm/hibernate/cfg/GrailsDomainBinder.java, plugin/src/test/groovy/gorm/tools/repository/errors/EntityValidationExceptionSpec.groovy, plugin/src/test/groovy/testing/Company.groovy, plugin/src/test/groovy/testing/Location.groovy, plugin/src/test/groovy/testing/Org.groovy, plugin/src/test/groovy/testing/OrgExt.groovy, plugin/src/test/groovy/testing/specs/ForeignIdGeneratorSpec.groovy
=> 100 naming strategy

docs/repository/ref.md, plugin/src/main/groovy/gorm/tools/repository/GormRepo.groovy, plugin/src/main/groovy/gorm/tools/repository/events/RepoEventPublisher.groovy, plugin/src/test/groovy/gorm/tools/repository/RepositoryEventPublisherSpec.groovy
Added docs and tests for Grails events #99
=> 99 tests for events

build.gradle, examples/benchmarks/grails-app/domain/gpbench/fat/CityFat.groovy, examples/benchmarks/grails-app/services/gpbench/BenchmarkDatabindingService.groovy, examples/benchmarks/src/main/groovy/gpbench/model/DatesTrait.groovy, plugin/src/main/groovy/gorm/tools/beans/DateUtil.groovy, plugin/src/main/groovy/gorm/tools/beans/IsoDateUtil.groovy, plugin/src/main/groovy/gorm/tools/beans/MapFlattener.groovy, plugin/src/main/groovy/gorm/tools/beans/MultiFormatDateConverter.groovy, plugin/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy, plugin/src/main/groovy/gorm/tools/mango/MangoBuilder.groovy, plugin/src/test/groovy/gorm/tools/beans/DateUtilSpec.groovy, plugin/src/test/groovy/gorm/tools/beans/MapFlattenerTest.groovy, plugin/src/test/groovy/gorm/tools/databinding/EntityMapBinderUnitSpec.groovy
=> 111 dateutil performance

plugin/src/main/groovy/gorm/tools/testing/DomainAutoTest.groovy, plugin/src/test/groovy/testing/Project.groovy, plugin/src/test/groovy/testing/ProjectSpec.groovy, plugin/src/test/groovy/testing/specs/ProjectSpec.groovy
=> 90 domain auto test

examples/test-app/build.gradle, examples/test-app/grails-app/conf/application.yml, examples/test-app/grails-app/domain/repoapp/Org.groovy, examples/test-app/src/integration-test/groovy/testing/JdbcTimeZoneSpec.groovy
=> #117 - set hibernate timezone to utc. 

plugin/src/main/groovy/gorm/tools/testing/DomainAutoTest.groovy, plugin/src/test/groovy/testing/Nested.groovy, plugin/src/test/groovy/testing/Project.groovy
=> DomainAutoTest associations handling #90

docs/working-with-dates.md
=> #117 - Add docs for timezone handling for dates

docs/repository/ref.md
=> #51 Add docs for refreshable beans

docs/repository/intro.md, docs/repository/ref.md, plugin/src/main/groovy/gorm/tools/testing/BuildExampleData.groovy, plugin/src/main/groovy/gorm/tools/testing/BuildExampleHolder.groovy, plugin/src/main/groovy/gorm/tools/testing/DomainAutoTest.groovy
=> 129 domain test refactoring

examples/benchmarks/README.md, examples/benchmarks/build.gradle, examples/benchmarks/grails-app/conf/application.groovy, examples/benchmarks/grails-app/conf/application.yml, examples/benchmarks/grails-app/conf/ehcache.xml, examples/benchmarks/grails-app/domain/gpbench/CityBaselineDynamic.groovy, examples/benchmarks/grails-app/domain/gpbench/CityDynamic.groovy, examples/benchmarks/grails-app/domain/gpbench/CityModelTrait.groovy, examples/benchmarks/grails-app/domain/gpbench/Country.groovy, examples/benchmarks/grails-app/domain/gpbench/Region.groovy, examples/benchmarks/grails-app/domain/gpbench/fat/CityFatNoTraits.groovy, examples/benchmarks/grails-app/init/gpbench/BootStrap.groovy, examples/benchmarks/grails-app/services/gpbench/BenchmarkRunnerService.groovy, examples/benchmarks/run-benchmarks.sh, examples/benchmarks/src/main/groovy/gpbench/benchmarks/BaseBenchmark.groovy, examples/benchmarks/src/main/groovy/gpbench/benchmarks/ReadBenchmark.groovy, examples/benchmarks/src/main/groovy/gpbench/benchmarks/UpdateBenchmark.groovy
Added benchmarks for read operations when using Second Level cache #84
=> 84 benchmarks 2nd lvl cache

docs/repository/ref.md
=> #51 update docs

examples/benchmarks/grails-app/services/gpbench/BenchmarkRunnerService.groovy, examples/benchmarks/src/main/groovy/gpbench/benchmarks/BaseBatchInsertBenchmark.groovy, examples/benchmarks/src/main/groovy/gpbench/benchmarks/BaseUpdateBenchmark.groovy, examples/benchmarks/src/main/groovy/gpbench/benchmarks/GparsBaseLineUpdateBenchmark.groovy, examples/benchmarks/src/main/groovy/gpbench/benchmarks/RepoUpdateBenchmark.groovy
=> #75 Benchmarks for updates

gradle/codenarc-rules.groovy, plugin/build.gradle, plugin/grails-app/init/grails/plugin/gormtools/Application.groovy, plugin/src/main/groovy/gorm/tools/databinding/MapBinder.groovy, plugin/src/main/groovy/gorm/tools/idgen/IdGenerator.groovy, plugin/src/main/groovy/gorm/tools/idgen/StringIdGenerator.groovy, plugin/src/main/groovy/gorm/tools/mango/api/MangoQueryApi.groovy, plugin/src/main/groovy/gorm/tools/repository/api/RepositoryApi.groovy, plugin/src/main/groovy/grails/plugin/gormtools/GormToolsGrailsPlugin.groovy
=> Add codenarc for @CompileStatic #138

docs/id-generation.md, examples/benchmarks/grails-app/conf/application.groovy, plugin/grails-app/conf/application.groovy, plugin/src/main/groovy/gorm/tools/hibernate/SpringBeanIdGenerator.groovy, plugin/src/test/groovy/testing/specs/ForeignIdGeneratorSpec.groovy
=> fixes #145

plugin/src/test/groovy/gorm/tools/beans/MapFlattenerSpec.groovy, plugin/src/test/groovy/gorm/tools/beans/MapFlattenerTest.groovy, plugin/src/test/groovy/gorm/tools/idgen/PooledIdGeneratorSpec.groovy, plugin/src/test/groovy/gorm/tools/repository/RepoUtilsSpec.groovy
Refactor some tests to use Spock (#154) and add new unit tests for PooledIdGenerator (rel #139)
=> 154 refactor tests

docs/repository/databinding.md, plugin/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy, plugin/src/test/groovy/gorm/tools/databinding/EntityMapBinderUnitSpec.groovy
Add an ability to bind associations with bindableTo property in domains
=> Add an ability to bind associations with bindableTo property in domains

examples/test-app/grails-app/domain/repoapp/Person.groovy, examples/test-app/src/integration-test/groovy/testing/EntityMapBinderSpec.groovy, plugin/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy
connect #214 
connect 9ci/rcm#4575
=> #214 Fix bindable - should work for reloadable env

examples/test-app/src/integration-test/groovy/testing/EntityMapBinderSpec.groovy, plugin/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy, plugin/src/test/groovy/gorm/tools/databinding/EntityMapBinderUnitSpec.groovy
=> #216 - Should be able to deep bind nested instance

examples/restify/src/integration-test/groovy/restify/OrgRestApiSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/AbstractOrgRepo.groovy
=> 323 collection handling

examples/restify/src/integration-test/groovy/restify/OrgRestApiSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy, rally-domain/src/main/groovy/yakworks/rally/activity/repo/ActivityRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/activity/ActivitySpec.groovy
=> Associations

commons/src/main/groovy/yakworks/commons/map/Maps.groovy, commons/src/test/groovy/yakworks/commons/map/MapsSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/BulkableRepo.groovy
=> 9ci/domain9#370 Bulkable fixes

examples/testify/src/integration-test/groovy/gorm/tools/repository/BulkableRepoIntegrationSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/job/JobRepoTrait.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/bulk/BulkableRepo.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/errors/api/ApiErrorHandler.groovy, gorm-tools/src/test/groovy/gorm/tools/repository/BulkableRepoSpec.groovy, gorm-tools/src/test/groovy/testing/Nested.groovy, gorm-tools/src/test/groovy/testing/Project.groovy, gorm-tools/src/test/groovy/testing/ProjectRepo.groovy
=> #339 Bulkable tests

examples/restify/src/integration-test/groovy/restify/BulkRestApiSpec.groovy, examples/restify/src/integration-test/groovy/restify/OrgRestApiSpec.groovy, gorm-tools/src/test/groovy/gorm/tools/repository/BulkableRepoSpec.groovy
=> Fix BulkRestApiSpec

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/members/OrgMemberServiceSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/OrgMemberService.groovy
=> #526 Handle orgdimensions for custAccount

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/members/OrgMemberServiceSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/OrgMemberService.groovy
was blowing up tests for CustAccount
=> reverts #407 which was for 9ci/domain9#526

gorm-tools-rest/src/main/groovy/gorm/tools/rest/controller/RestRegistryResponder.groovy, gorm-tools-rest/src/main/groovy/gorm/tools/rest/controller/RestRepoApiController.groovy, gorm-tools/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy, gorm-tools/src/test/groovy/gorm/tools/databinding/EntityMapBinderUnitSpec.groovy
=> 9ci/domain9#597 Empty strings should be set as null

commons/src/test/groovy/yakworks/commons/lang/DateUtilSpec.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgRepoTests.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/members/OrgMemberServiceSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/OrgMemberService.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/AbstractOrgRepo.groovy
- Some ignored test fixed, 
- Fix https://github.com/9ci/domain9/issues/526
=> Test fixes

examples/restify/src/integration-test/groovy/restify/BulkCsvSpec.groovy, gorm-tools-csv/src/main/groovy/gorm/tools/csv/CSVPathKeyMapReader.groovy, gorm-tools-csv/src/test/groovy/gorm/tools/csv/CSVPathKeyMapReaderSpec.groovy, gorm-tools-csv/src/test/resources/KitchenSink.short.csv, gorm-tools-rest/src/main/groovy/gorm/tools/rest/controller/RestRepoApiController.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/bulk/BulkableRepo.groovy
=> 9ci/domain9#777 - Fix CSV path key map reader to initialize map 

examples/restify/src/integration-test/groovy/restify/BulkCsvSpec.groovy, examples/restify/src/integration-test/groovy/restify/BulkRestApiSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobContext.groovy
=> #491 Fix Bulk response json, update & fix tests

examples/restify/grails-app/conf/restapi/org.yml, examples/restify/src/integration-test/groovy/restify/BulkRestApiSpec.groovy
connect 9ci/domain9#726
Remove ignore, and add more test to verify success/error includes
=>  9ci/domain9#726 Add tests

examples/restify/src/integration-test/groovy/restify/OrgControllerTests.groovy, gorm-tools-rest/src/main/groovy/gorm/tools/rest/controller/RestRepoApiController.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/api/QueryArgs.groovy
=> fix includesKey and includes getting picked up as fields.

examples/testify/src/integration-test/groovy/gorm/tools/repository/BulkableRepoIntegrationSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobContext.groovy
=>  don't put error if it's empty list

examples/testify/src/integration-test/groovy/gorm/tools/repository/BulkableRepoIntegrationSpec.groovy
connect https://github.com/9ci/domain9/issues/888
=> 9ci/domain9#888 Test to verify data is present when bulk fails with error

examples/testify/src/integration-test/groovy/gorm/tools/job/SyncJobEventsSpec.groovy, examples/testify/src/integration-test/groovy/gorm/tools/repository/BulkableRepoIntegrationSpec.groovy, examples/testify/src/main/groovy/yakworks/testify/SyncjobEventListener.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobArgs.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobContext.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobFinishedEvent.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobService.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobStartEvent.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobState.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/bulk/BulkableRepo.groovy, gorm-tools/src/test/groovy/gorm/tools/job/SyncJobImplSpec.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/job/SyncJobContextTests.groovy
connect https://github.com/9ci/domain9/issues/926
=> basic design flushed out

commons/src/main/groovy/yakworks/commons/io/FileUtil.groovy, commons/src/test/groovy/yakworks/commons/io/FileUtilTests.groovy, examples/resources/zip/test.txt
=> Update zip util to zip directories recursively

examples/testify/src/integration-test/groovy/gorm/tools/repository/BulkableRepoIntegrationSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/bulk/BulkableRepo.groovy
=> 9ci/domain9#1118 Add test, replace handleUnexpected with handleException

gorm-tools/src/main/groovy/gorm/tools/utils/DbUtils.groovy
=> Add query utils

gorm-tools/src/test/groovy/gorm/tools/mango/MangoCriteriaSpec.groovy, gorm-tools/src/test/groovy/testing/TestSource.groovy
connect #285
Looks like the issue has been fixed, I have just added test tht verifies the fix @basejump
=> #285 Add test for id criteria restriction

gorm-tools/src/test/groovy/gorm/tools/repository/BulkableRepoSpec.groovy
=> #474 Add tests for buildErrorMap & buildSuccessMap

examples/rally-api/src/integration-test/groovy/yakworks/rest/ExerciseRestApiSpec.groovy, examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgWebApiSpec.groovy, examples/testify/src/integration-test/groovy/gorm/tools/async/ParallelToolsSpecSpec.groovy, examples/testify/src/integration-test/groovy/gorm/tools/security/AppUserDetailsServiceSpec.groovy, gorm-etl/src/test/groovy/yakworks/etl/csv/CSVPathKeyMapReaderSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/MangoBuilder.groovy, gorm-tools/src/test/groovy/gorm/tools/problem/ProblemHandlerSpec.groovy, gorm-tools/src/test/groovy/gorm/tools/validation/DomainValidationSpec.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgRepoTests.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/security/RallyUserServiceSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/AbstractOrgRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/attachment/AttachmentSpec.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/model/SecRoleUser.groovy
connect #478
Some of the FIXMEs for #478
=> #478 Handle XXX / FIXME

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/ContactTests.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy
Fixes 9ci/domain9#477
Old PR - https://github.com/yakworks/gorm-tools/pull/565
=> Delete location with contact

examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgMangoControllerTests.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/MangoDetachedCriteria.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/hibernate/HibernateMangoQuery.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/jpql/JpqlQueryBuilder.groovy, gorm-tools/src/test/groovy/gorm/tools/mango/jpql/JpqlQueryBuilderSelectSpec.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/mango/JpqlQueryBuilderSelectTests.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/mango/OrgMangoProjectionTests.groovy
connect https://github.com/yakworks/gorm-tools/pull/206
This PR removes the suffixies eg _sum, _count
=> #603 Keep original property name in projections, dont prefix _sum etc

rally-domain/src/main/groovy/yakworks/rally/common/BaseArScoreCard.groovy
=> 9ci/domain9#1586 - Orgcalc amounts defaults to zero

examples/rally-api/src/main/resources/config/datasource.yml, gorm-rest/src/main/groovy/yakworks/rest/gorm/render/SyncJobRenderer.groovy, gorm-tools/src/main/groovy/gorm/tools/async/AsyncService.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobArgs.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobContext.groovy, gorm-tools/src/main/groovy/gorm/tools/job/SyncJobEntity.groovy, gorm-tools/src/main/groovy/yakworks/gorm/api/PathItem.groovy, gorm-tools/src/main/groovy/yakworks/gorm/boot/GormToolsConfiguration.groovy, gorm-tools/src/test/groovy/gorm/tools/hibernate/json/JsonSample.groovy, gorm-tools/src/test/groovy/testing/TestSyncJob.groovy, rally-domain/build.gradle, rally-domain/grails-app/init/yakworks/rally/Application.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/JdbcTemplateSpec.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/job/SyncJobContextTests.groovy, rally-domain/src/main/groovy/yakworks/rally/job/SyncJob.groovy, rally-domain/src/main/groovy/yakworks/rally/job/SyncJobRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/job/SyncJobSpec.groovy
=> 1562 syncjob error field

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/ContactTests.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/model/ContactSource.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactSourceRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactRepoSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactSourceRepoSpec.groovy
=> 9ci/domain9#1668 Contact update with source id

gorm-tools/src/test/groovy/gorm/tools/mango/jpql/JpqlQueryBuilderSelectSpec.groovy
=> Add a test for restrictions on a projection with alias

gorm-tools/src/main/groovy/gorm/tools/repository/model/AbstractCrossRefRepo.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/activity/ActivityContactOpTests.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/tag/TagDataOpSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/activity/repo/ActivityRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/attachment/repo/AttachmentRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/AbstractOrgRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/tag/TagLinkSpec.groovy
=> Fix tags handling domain9#1708

gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/RestApiController.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/api/QueryArgs.groovy, gorm-tools/src/main/groovy/yakworks/gorm/api/ApiUtils.groovy, gorm-tools/src/main/groovy/yakworks/gorm/config/GormConfig.groovy, gorm-tools/src/test/groovy/yakworks/gorm/api/ApiUtilsSpec.groovy
=> 9ci/domain9#1924 Parse params from query 

examples/rally-api/src/integration-test/groovy/yakworks/rest/ExerciseRestApiSpec.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/BulkControllerSupport.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/EntityResponder.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/RestRegistryResponder.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/RestRepoApiController.groovy
=> #1925 Handle and report back bad query in q param

examples/rally-api/src/integration-test/groovy/yakworks/rest/RestErrorsSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/MangoDetachedCriteria.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgRepoTests.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgSourceRepoTests.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/members/OrgMemberSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/OrgSourceRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/OrgSourceRepoSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/OrgSpec.groovy
=> 1941 check if orgsource exists

examples/rally-api/src/integration-test/groovy/yakworks/security/TokenRestApiSpec.groovy, security/boot-security/src/main/groovy/yakworks/security/spring/token/TokenController.groovy
=> 9ci/domain9#2012 - error handler for oauth token controller

gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/BulkControllerSupport.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/RestRepoApiController.groovy
=> #1997 log errors for bulk operation exception

examples/testify/src/integration-test/groovy/gorm/tools/security/AppUserRepoSpec.groovy, gorm-audit/src/test/groovy/yakworks/security/audit/AuditStampAnnSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/activity/model/Task.groovy, rally-domain/src/main/groovy/yakworks/rally/activity/model/TaskStatus.groovy, rally-domain/src/main/groovy/yakworks/rally/activity/model/TaskType.groovy, rally-domain/src/test/groovy/yakworks/rally/RallyEventListenerSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/activity/ActivityServiceSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactSpec.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/model/AppUserRepo.groovy, security/boot-security-gorm/src/test/groovy/yakworks/security/audit/AuditStampAnnSpec.groovy, security/boot-security-gorm/src/test/groovy/yakworks/security/gorm/PasswordValidatorSpec.groovy
=> 9ci/domain9#2010 - Check for username/email uniqueness

examples/testify/src/integration-test/groovy/gorm/tools/security/AppUserRepoSpec.groovy
=> Fix uniue username tests

examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgRestApiSpec.groovy, examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgWebApiSpec.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/ContactTests.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/EmailUtils.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/model/Contact.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/model/ContactSource.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactSourceRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/OrgRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/seed/RallySeed.groovy, rally-domain/src/test/groovy/yakworks/rally/activity/ActivityContactSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/activity/ActivityServiceSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactIncludesSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactRepoSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactSourceRepoSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactSpec.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/OrgCopierSpec.groovy, version.properties
=> 9ci/domain9#2013 Fix contact lookup by sourceid

examples/rally-api/src/integration-test/groovy/yakworks/rest/ExerciseRestApiSpec.groovy, gradle.properties, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/ContactTests.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactRepoSpec.groovy
=> Add tests for contact create

examples/testify/src/integration-test/groovy/gorm/tools/audit/AuditStampOrgSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy, gorm-tools/src/test/groovy/gorm/tools/databinding/EntityMapBinderUnitSpec.groovy
connect https://github.com/9ci/domain9/pull/2128
=> Data binder fix 

rally-domain/src/main/groovy/yakworks/rally/orgs/model/Contact.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/model/Org.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/AbstractOrgRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactRepoSpec.groovy
=> 9ci/cust-rndc-ext#174 set contact as primary contact - if isPrimary=true

examples/testify/src/integration-test/groovy/testing/EntityMapBinderSpec.groovy, gorm-tools/src/main/groovy/gorm/tools/databinding/EntityMapBinder.groovy, gorm-tools/src/main/groovy/gorm/tools/databinding/EntityMapBindingListener.groovy, gorm-tools/src/main/groovy/gorm/tools/metamap/services/MetaMapService.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/model/AbstractCrossRefRepo.groovy, gorm-tools/src/main/groovy/gorm/tools/utils/GormMetaUtils.groovy, gorm-tools/src/test/groovy/gorm/tools/utils/GormMetaUtilsSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/model/Contact.groovy
Related : https://github.com/9ci/cust-rndc-ext/issues/222
=> Fix binder to handle hibernate proxies

examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgWebApiSpec.groovy, examples/testify/src/integration-test/groovy/gorm/tools/repository/KitchenSinkRepoIntegrationTest.groovy, gorm-test-domain/src/main/groovy/yakworks/testing/gorm/model/KitchenSink.groovy, gorm-tools/src/main/groovy/gorm/tools/metamap/services/MetaMapService.groovy, gorm-tools/src/main/groovy/gorm/tools/problem/ProblemHandler.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/GormRepo.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/errors/RepoExceptionSupport.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/model/AbstractCrossRefRepo.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/JdbcTemplateSpec.groovy
connect #721  
connect https://github.com/9ci/domain9/issues/2198
=> Fix to handle db exceptions and convert to problem during remove

examples/rally-api/src/integration-test/groovy/yakworks/security/BasicAuthLoginSpec.groovy, examples/testify/src/integration-test/groovy/gorm/tools/security/AppUserDetailsServiceSpec.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/model/AppUser.groovy
connect https://github.com/9ci/domain9/issues/2222
=> login should be case insensitive

gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/RestApiController.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/RestRepoApiController.groovy, gorm-tools/src/main/groovy/gorm/tools/problem/ProblemHandler.groovy, gorm-tools/src/test/groovy/gorm/tools/problem/ProblemHandlerSpec.groovy
=> Handle broken pipe exception

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/ContactSourceRepoTests.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/ContactSourceRepo.groovy, rally-domain/src/test/groovy/yakworks/rally/orgs/ContactSpec.groovy
connect https://github.com/9ci/domain9/issues/2255
=> #2255 Add check for contact source unique key

examples/rally-api/src/integration-test/groovy/yakworks/rest/ExKitchenSinkApiSpec.groovy, examples/rally-api/src/integration-test/groovy/yakworks/rest/ExerciseRestApiSpec.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/RestRepoApiController.groovy
https://github.com/9ci/domain9/issues/2292
=> support bindId during post

gorm-etl/src/main/groovy/yakworks/etl/excel/ExcelBuilder.groovy
Connect : https://github.com/9ci/domain9/issues/2323
=> Catch exception

gorm-tools/src/main/groovy/gorm/tools/hibernate/type/JsonType.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/MangoTidyMap.groovy, gorm-tools/src/main/groovy/gorm/tools/problem/ProblemHandler.groovy, gorm-tools/src/test/groovy/gorm/tools/mango/MangoTidyMapSpec.groovy
=>  Fix tidy map to use id for inquery if key exist in map list

gorm-tools/src/main/groovy/gorm/tools/mango/jpql/PagedQuery.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/mango/OrgMangoProjectionTests.groovy
https://github.com/9ci/cust-rndc-ext/issues/325
https://github.com/9ci/domain9/pull/2440
=> mapList - pagination & totalCount fix

gorm-tools/src/main/groovy/gorm/tools/mango/MangoBuilder.groovy, gorm-tools/src/test/groovy/gorm/tools/mango/MangoCriteriaSpec.groovy, gorm-tools/src/test/groovy/testing/Cust.groovy
With this change, the tests of pr https://github.com/9ci/domain9/pull/2432 Passes
=> Support querying by uuid string

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgRepoTests.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/members/OrgServiceSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/OrgService.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/OrgRepo.groovy
Related : https://github.com/9ci/domain9/pull/2439/files
=> get org from q criteria

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgTagTests.groovy, rally-domain/src/main/groovy/yakworks/rally/activity/repo/ActivityRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/model/OrgTag.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/OrgRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/OrgTagRepo.groovy, rally-domain/src/main/groovy/yakworks/rally/tag/repo/TagLinkRepo.groovy
Related : https://github.com/9ci/domain9/issues/2455
=> Support searching customer / account by tags

rally-domain/src/integration-test/groovy/yakworks/rally/mail/services/CommonMailerTests.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/mailgun/MailgunService.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/services/CommonMailer.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/services/MailMessageSender.groovy, rally-domain/src/test/groovy/yakworks/rally/extensions/AppTimeZoneSpec.groovy
connect : https://github.com/9ci/domain9/pull/2513
=> Support html emails for paymailer

rally-domain/src/integration-test/groovy/yakworks/rally/mail/services/CommonMailerTests.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/mailgun/MailgunService.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/services/CommonMailer.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/services/MailMessageSender.groovy, rally-domain/src/test/groovy/yakworks/rally/extensions/AppTimeZoneSpec.groovy
* Support html emails for paymailer
* Fix tests which are failing because of daylight saving time change
=> Support html emails for paymailer (#779)

gorm-tools/src/main/groovy/gorm/tools/mango/MangoBuilder.groovy, gorm-tools/src/test/groovy/gorm/tools/mango/MangoCriteriaSpec.groovy
=>  Mango query : Throw error for invalid/missing prop

gorm-etl/src/main/groovy/yakworks/etl/excel/ExcelBuilderSupport.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/render/XlsxPagerRenderer.groovy
=> use grid config and uiList for export to excel

gorm-rest/src/main/groovy/yakworks/rest/log/InvalidApiCallEvent.groovy
Related to : https://github.com/9ci/domain9/pull/2520
=> InvalidApiCallEvent cleanup

examples/rally-api/src/integration-test/groovy/yakworks/hibernate/GormToolsTrxManagerPostProcessorSpec.groovy, examples/rally-api/src/main/resources/application-test.yml, gorm-tools/src/main/groovy/gorm/tools/hibernate/GormtoolsTrxManagerBeanPostProcessor.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/hibernate/HibernateMangoQuery.groovy, gorm-tools/src/main/groovy/yakworks/gorm/boot/GormToolsConfiguration.groovy
=>  Default query timeout

examples/testify/src/integration-test/groovy/testing/CodeAsIdSpec.groovy, gorm-test-domain/src/main/groovy/yakworks/testing/gorm/model/ThingStringId.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/model/StringIdRepoEntity.groovy
9ci/domain9#1848
https://github.com/9ci/domain9/issues/2599
=>  Code as String ID

rally-domain/src/main/groovy/yakworks/rally/mail/mailgun/MailgunService.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/services/MailMessageSender.groovy
https://github.com/9ci/cust-rndc-ext/issues/524
=>  Mail gun error log

examples/rally-api/src/integration-test/groovy/yakworks/rest/BulkCsvSpec.groovy, examples/resources/csv/contact-update.csv, gorm-etl/src/main/groovy/yakworks/etl/csv/CSVPathKeyMapReader.groovy, gorm-etl/src/test/groovy/yakworks/etl/csv/CSVPathKeyMapReaderSpec.groovy, gorm-etl/src/test/resources/KitchenSink.short.csv
If "null" string is passed then convert to null so updates using CSV can blank out fields.  Csv Fix : empty value with "null" string
=> Csv Fix : convert "null" string to null (#809)

rally-domain/src/integration-test/groovy/yakworks/rally/mail/services/MailMessageSenderSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/EmailService.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/EmailUtils.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/mailgun/MailgunService.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/services/MailMessageSender.groovy, rally-domain/src/test/groovy/yakworks/rally/mail/EmailUtilsSpec.groovy
https://github.com/9ci/domain9/issues/2708
=> Mail validation

gorm-test-domain/src/main/groovy/yakworks/testing/gorm/model/Thing.groovy, gorm-tools/src/main/groovy/gorm/tools/mango/jpql/KeyExistsQuery.groovy, gorm-tools/src/main/groovy/gorm/tools/repository/model/PersistableRepoEntity.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgRepoTests.groovy
closes https://github.com/yakworks/gorm-tools/issues/831
=> Fix static exists on entity

examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgControllerTests.groovy, gorm-tools/grails-app/i18n/messages.yml, gorm-tools/src/main/groovy/gorm/tools/mango/api/QueryArgs.groovy
=> Add qInvalid msg 

gorm-tools/src/main/groovy/gorm/tools/problem/ProblemHandler.groovy
=> Update ProblemHandler to prevent ArrayIndexOutOfBound

examples/rally-api/grails-app/controllers/yakworks/rally/api/rally/OrgController.groovy, examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgRestApiSpec.groovy, gorm-etl/src/main/groovy/yakworks/etl/csv/CSVPathKeyMapReader.groovy, gorm-etl/src/main/groovy/yakworks/etl/excel/ExcelBuilder.groovy, gorm-etl/src/main/groovy/yakworks/etl/excel/ExcelBuilderSupport.groovy, gorm-etl/src/main/groovy/yakworks/etl/excel/ExcelUtils.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/controller/CrudApiController.groovy, gorm-rest/src/main/groovy/yakworks/rest/gorm/render/XlsxPagerRenderer.groovy, rally-domain/src/test/groovy/yakworks/rally/common/ZonedDateUtilSpec.groovy
=> Fix for excel to export issue with caching turned on 

examples/rally-api/src/integration-test/groovy/yakworks/rest/ExcelExportSpec.groovy, examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgRestApiSpec.groovy, examples/rally-api/src/main/resources/restapi/rally/org.yml, gorm-etl/src/main/groovy/yakworks/etl/excel/ExcelBuilderSupport.groovy
Related 
https://github.com/9ci/domain9/pull/2914
https://github.com/9ci/domain9/issues/2888
=> xls export fix & tests

rally-domain/src/main/groovy/yakworks/rally/mail/mailgun/MailgunService.groovy
=> Mailgun : Log error

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/members/OrgServiceSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/OrgService.groovy
This reverts commit b82173aca43bc8b376934efd7f86bf70cef670a1.
=> put back Company member change

rally-domain/src/integration-test/groovy/yakworks/rally/mail/model/MailMessageSpec.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/model/MailMessage.groovy
=> MailMessage.msgResponse increase maxSize constrait

rally-domain/src/integration-test/groovy/yakworks/rally/activity/ActivityTests.groovy, rally-domain/src/main/groovy/yakworks/rally/activity/repo/ActivityRepo.groovy
=> Activity create : NPE fix

rally-domain/src/main/groovy/yakworks/rally/mail/EmailService.groovy, rally-domain/src/main/groovy/yakworks/rally/mail/mailgun/MailgunService.groovy, rally-domain/src/test/groovy/yakworks/rally/mail/MailgunServiceSpec.groovy
https://github.com/9ci/domain9/issues/3122
=> Mailgun API 500 Retry

gorm-tools/src/main/groovy/gorm/tools/job/SyncJobService.groovy
=> Log error before handleUnexpected

gorm-rest/src/main/groovy/yakworks/rest/gorm/render/XlsxPagerRenderer.groovy
=> Handle exception during excel file rendering

rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgRepoTests.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/AbstractOrgRepo.groovy
=> Fix : Update org's primary location : Dont create new

examples/rally-api/src/integration-test/groovy/yakworks/rest/OrgRestApiSpec.groovy, rally-domain/src/integration-test/groovy/yakworks/rally/orgs/OrgRepoTests.groovy, rally-domain/src/main/groovy/yakworks/rally/orgs/repo/AbstractOrgRepo.groovy
=> org update : Do not create empty locations

gorm-tools/src/main/groovy/gorm/tools/mango/MangoTidyMap.groovy, gorm-tools/src/test/groovy/gorm/tools/mango/MangoTidyMapSpec.groovy
fixes https://github.com/9ci/domain9/issues/3191
will convert * to % when like or ilike are specified.
=> ilike start to pct fix

examples/rally-api/src/integration-test/groovy/yakworks/rest/UserRestApiSpec.groovy, examples/testify/src/integration-test/groovy/gorm/tools/security/AppUserRepoSpec.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/AppUserPasswordValidator.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/AppUserService.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/api/UserSecurityConfig.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/model/AppUserRepo.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/model/SecPasswordHistoryRepo.groovy, security/boot-security-gorm/src/main/groovy/yakworks/security/gorm/testing/SecuritySeedData.groovy, security/boot-security-gorm/src/test/groovy/yakworks/security/gorm/AppUserSpec.groovy, security/boot-security-gorm/src/test/groovy/yakworks/security/gorm/PasswordSpec.groovy, security/boot-security/src/main/groovy/yakworks/security/PasswordConfig.groovy, security/boot-security/src/main/resources/messages.properties
review these commits for previous changes
https://github.com/yakworks/gorm-tools/commit/707088c4f5f5fb399eb3d1c5a9e89f204443bd8e
https://github.com/yakworks/gorm-tools/commit/20426d9866ac786ec26959e7db906ab466cece77
=> Security tripx
